VPATH=Framework:Framework/Allocation:Framework/Allocation/Hierachal:Framework/Allocation/Update:\
Framework/Audio:Framework/Audio/Sample:Framework/Audio/Track:\
Framework/Configurations:\
Framework/Devices:\
Framework/Exception:\
Framework/Graphic:Framework/Graphic/Map:\
Framework/Host:\
Framework/Input:Framework/Input/Commands:Framework/Input/Handler:Framework/Input/KeyBindings:\
Framework/IO:Framework/IO/Stores:Framework/IO/Api:\
Framework/Output:Framework/Output/Panels:Framework/Output/Bluetooths:\
Framework/Database:\
Framework/Scenes:\
Framework/Threading:\
Framework/Timing:Framework/Timing/SpeedAdjusters:\
\
Games:Games/Configurations:Games/Input:\
Games/Ruleset:Games/Ruleset/Modifiers:Games/Ruleset/Judgements:Games/Ruleset/Scoring:Games/Ruleset/Replays:\
Games/Scene:Games/Scene/Interlude:Games/Scene/Play:Games/Scene/Play/Hud:Games/Scene/Select:Games/Scene/Results:\
Games/Input:Games/Input/Commands:\
Games/Output:Games/Output/Bluetooths:Games/Output/Bluetooths/Commands:\
Games/Scheduler/Event:Games/Scheduler/Event/ControlPoints:Games/Scheduler/Event/Effect:\
Games/Scheduler/Event/Effect/Algorithm:Games/Scheduler/Event/GameEvents:Games/Scheduler/Event/SystemEvents:\
Games/Scheduler/Event/IoEvents:Games/Scheduler/Event/IoEvents/IoCommunicators:\
Games/Scheduler/Event/InstrumentEvents:Games/Scheduler/Event/InstrumentEvents/InstrumentControllers:\
Games/Scheduler/Event/PlayfieldEvents:Games/Scheduler/Event/PlayfieldEvents/PlayfieldControllers:\
Games/Scheduler/Event/TimeEvents:Games/Scheduler/Event/TimeEvents/TimeControllerControllers:\
Games/Sheetmusic:Games/Sheetmusic/Format:Games/Sheetmusic/Format/Parser:Games/Sheetmusic/IO:Games/Sheetmusic/Pattern:\
Games/Timing:\
Games/UI:\
Games/Users:\
\
Instruments:Instruments/Audio:Instruments/Input:\
\
Util:Util/DataStructure:\
\
ThirdParty/Bass:\
\
Desktop:Desktop/Devices:\
\
RulesetMeteor:RulesetMeteor/Config:RulesetMeteor/Input:RulesetMeteor/Play:\
RulesetMeteor/Output/Panels:\
RulesetMeteor/Ruleset:RulesetMeteor/Ruleset/Modifiers:RulesetMeteor/Ruleset/Judgements:RulesetMeteor/Ruleset/Scoring:RulesetMeteor/Ruleset/Replays:\
RulesetMeteor/Scenes/Results:\
RulesetMeteor/Scheduler/Event:RulesetMeteor/Scheduler/Event/ControlPoints:RulesetMeteor/Scheduler/Event/Effect:RulesetMeteor/Scheduler/Event/Effect/Algorithm:\
RulesetMeteor/Scheduler/Event/IoEvents:RulesetMeteor/Scheduler/Event/IoEvents/IoCommunicators:\
RulesetMeteor/Scheduler/Event/InstrumentEvents:RulesetMeteor/Scheduler/Event/InstrumentEvents/InstrumentControllers:\
RulesetMeteor/Scheduler/Event/PlayfieldEvents:RulesetMeteor/Scheduler/Event/PlayfieldEvents/PlayfieldControllers:\
RulesetMeteor/Scheduler/Event/TimeEvents:RulesetMeteor/Scheduler/Event/TimeEvents/TimeControllerControllers:\
RulesetMeteor/Sheetmusic:RulesetMeteor/Sheetmusic/Pattern:\
RulesetMeteor/Timing:\




INCLUDE = -IFramwork -IFramework/Allocation -IFramework/Allocation/Hierachal -IFramework/Allocation/Update \
-IFramework/Audio -IFramework/Audio/Sample -IFramework/Audio/Track \
-IFramework/Configurations \
-IFramework/Devices \
-IFramework/Exception \
-IFramework/Graphic -IFramework/Graphic/Map \
-IFramework/Host \
-IFramework/Input -IFramework/Input/Commands -IFramework/Input/Handler -IFramework/Input/KeyBindings \
-IFramework/IO -IFramework/IO/Stores -IFramework/IO/Api \
-IFramework/Output -IFramework/Output/Panels -IFramework/Output/Bluetooths \
-IFramework/Database \
-IFramework/Scenes \
-IFramework/Threading \
-IFramework/Timing -IFramework/Timing/SpeedAdjusters \
\
-IGames -IGames/Configurations -IGames/Input \
-IGames/Ruleset -IGames/Ruleset/Modifiers -IGames/Ruleset/Judgements -IGames/Ruleset/Scoring -IGames/Ruleset/Replays \
-IGames/Scene -IGames/Scene/Interlude -IGames/Scene/Play -IGames/Scene/Play/Hud -IGames/Scene/Select -IGames/Scene/Results \
-IGames/Input -IGames/Input/Commands \
-IGames/Output -IGames/Output/Bluetooths -IGames/Output/Bluetooths/Commands \
-IGames/Scheduler/Event -IGames/Scheduler/Event/ControlPoints -IGames/Scheduler/Event/Effect \
-IGames/Scheduler/Event/Effect/Algorithm -IGames/Scheduler/Event/GameEvents -IGames/Scheduler/Event/SystemEvents \
-IGames/Scheduler/Event/IoEvents -IGames/Scheduler/Event/IoEvents/IoCommunicators \
-IGames/Scheduler/Event/InstrumentEvents -IGames/Scheduler/Event/InstrumentEvents/InstrumentControllers \
-IGames/Scheduler/Event/PlayfieldEvents -IGames/Scheduler/Event/PlayfieldEvents/PlayfieldControllers \
-IGames/Scheduler/Event/TimeEvents -IGames/Scheduler/Event/TimeEvents/TimeControllerControllers \
-IGames/Sheetmusic -IGames/Sheetmusic/Format -IGames/Sheetmusic/Format/Parser -IGames/Sheetmusic/IO -IGames/Sheetmusic/Pattern \
-IGames/Timing \
-IGames/UI \
-IGames/Users \
\
-IInstruments -IInstruments/Audio -IInstruments/Input \
\
-IUtil -IUtil/DataStructure \
\
-IThirdParty/Bass \
\
-IDesktop -IDesktop/Devices \
\
-IRulesetMeteor -IRulesetMeteor/Config -IRulesetMeteor/Input -IRulesetMeteor/Output -IRulesetMeteor/Output/Panels \
-IRulesetMeteor/Play -IRulesetMeteor/Ruleset -IRulesetMeteor/Ruleset/Modifiers -IRulesetMeteor/Ruleset/Judgements -IRulesetMeteor/Ruleset/Scoring -IRulesetMeteor/Ruleset/Replays \
-IRulesetMeteor/Scenes/Results \
-IRulesetMeteor/Scheduler/Event -IRulesetMeteor/Scheduler/Event/ControlPoints -IRulesetMeteor/Scheduler/Event/Effect -IRulesetMeteor/Scheduler/Event/Effect/Algorithm \
-IRulesetMeteor/Scheduler/Event/IoEvents -IRulesetMeteor/Scheduler/Event/IoEvents/IoCommunicators \
-IRulesetMeteor/Scheduler/Event/InstrumentEvents -IRulesetMeteor/Scheduler/Event/InstrumentEvents/InstrumentControllers \
-IRulesetMeteor/Scheduler/Event/PlayfieldEvents -IRulesetMeteor/Scheduler/Event/PlayfieldEvents/PlayfieldControllers \
-IRulesetMeteor/Scheduler/Event/TimeEvents -IRulesetMeteor/Scheduler/Event/TimeEvents/TimeControllerControllers \
-IRulesetMeteor/Sheetmusic -IRulesetMeteor/Sheetmusic/Pattern \
-IRulesetMeteor/Timing 


#INCLUDE = -IGames -IGames/Config -IGames/Graphic -IGames/Graphic/Map -IGames/Graphic/Renderer -IGames/Play -IGames/Ruleset \
#-IGames/Scheduler -IGames/Scheduler/Event -IGames/Scheduler/Event/ControlPoints -IGames/Scheduler/Event/GameEvents -IGames/Scheduler/Event/Effect \
#-IGames/Scheduler/Event/GameEvents -IGames/Scheduler/Event/SystemEvents \
#-IGames/Sheetmusic -IGames/Sheetmusic/Pattern -IGames/Sheetmusic/IO -IGames/Sheetmusic/Format \
#-IRulesetMeteor -IRulesetMeteor/Config -IRulesetMeteor/Graphic -IRulesetMeteor/Graphic/Renderer \
#-IRulesetMeteor/Play -IRulesetMeteor/Scheduler/Event/Effect -IRulesetMeteor/Scheduler/Event/Effect/Algorithm \
#-IRulesetMeteor/Sheetmusic -IRulesetMeteor/Sheetmusic/Pattern \
#-IUtil -IUtil/Hierachal -IUtil/Update

#INCLUDE = -IGames -IGames/Config -IGames/Graphic -I./Games/Graphic/Map -I./Games/Graphic/Renderer -I./Games/Play:Games/Ruleset \
#-I./Games/Scheduler -I./Games/Scheduler/Event -I./Games/Scheduler/Event/ControlPoints -I./Games/Scheduler/Event/Effect \
#-I./RulesetMeteor -I./RulesetMeteor/Config -I./RulesetMeteor/Graphic -I./RulesetMeteor/Graphic/Renderer \
#-I./RulesetMeteor/Play -I./RulesetMeteor/Scheduler/Event/Effect -I./RulesetMeteor/Scheduler/Event/Effect/Algorithm \
#-I./RulesetMeteor/Sheetmusic -I./RulesetMeteor/Sheetmusic/Pattern \
#-I./Util -I./Util/Hierachal -I./Util/Update




TARGET  = MeteoKB
#compiler 
CC = g++
#cflags 
CFLAGS = -Wall -ansi -s -std=c++14 -pthread -lbass -lstdc++fs -lbluetooth -DFIRMWARE_VERSION=0x0
#object 
OBJS = Main.o \
\
Base.o Game.o \
Cachable.o ChildAddable.o Container.o HasParent.o Loadable.o LoadStateHandler.o MtoObject.o Schedulable.o Scheduler.o Triggerable.o Updatable.o \
AdjustableAudioComponent.o AudioComponent.o AudioManager.o \
BassSample.o BassSampleChannel.o MultiPlaybackBassSampleChannel.o Sample.o SampleChannel.o MultiPlaybackSampleChannel.o DualPlaybackBassSampleChannel.o SampleManager.o \
BassTrack.o RateSettableBassTrack.o Track.o TrackManager.o \
ConfigManager.o FrameworkConfigManager.o \
DatabaseContext.o DatabaseContextFactory.o DatabaseStore.o FakeMeteoDatabaseContext.o MeteoDatabaseContext.o ReadonlyCsvDatabaseContextFactory.o MemoryBasedDatabaseContextFactory.o \
BluetoothDevice.o Device.o DisplayDevice.o InputDevice.o OutputDevice.o KeyboardDevice.o PanelDevice.o \
Drawable.o Map.o \
GameHost.o MeteoGameHost.o \
BluetoothState.o CustomInputManager.o InputManager.o InputState.o KeyboardState.o PanelState.o PassThroughInputManager.o HasInputKey.o \
BluetoothCommand.o BluetoothInputHandler.o KeyboardInputHandler.o PanelInputHandler.o KeyBindingStore.o \
BluetoothPhone.o Display.o FileStore.o Keyboard.o MainInterface.o Panel.o Peripheral.o PlatformStorage.o Storage.o StorageResourceStore.o DynamicPathResourceStore.o ApiAccess.o \
OutputManager.o BluetoothOutputer.o \
Scene.o \
GameThread.o ThreadMaster.o \
DecoupledInterpolatingFramedClock.o FramedClock.o InterpolatingFramedClock.o OffsetFramedClock.o StopwatchClock.o ThrottledFramedClock.o TimeController.o \
LinearSpeedAdjuster.o SpeedAdjuster.o \
\
MeteoGame.o MeteoGameBase.o \
MeteoConfigManager.o \
Ruleset.o RulesetInfo.o RulesetStore.o Judgement.o HasHitWindow.o HitWindow.o ReplayRecorder.o ReplayFrame.o \
Modifier.o DifficultyModifier.o EventProcessorFilterModifier.o InstrumentModifier.o TimeControllerModifier.o \
ScoreProcessor.o \
MeteoBluetoothCommand.o MeteoAckFileBluetoothCommand.o \
MeteoBluetoothMessage.o MeteoBluetoothOutputer.o MeteoContextBluetoothMessage.o MeteoFileBluetoothMessage.o MeteoOutputFileBluetoothCommand.o \
Loader.o MeteoScene.o Intro.o Player.o PlayerLoader.o Playfield.o Result.o \
HudDisplay.o JudgementFlasher.o SongProgress.o \
MainMenu.o PlaySongSelect.o SongSelect.o \
Event.o EventProcessorMaster.o EventProcessorFilter.o HitObject.o DynamicEventGenerator.o \
ControlPoint.o NoteControlPoint.o NoteControlPointHitObject.o PlayableControlPoint.o InputKeyControlPoint.o InputKeyControlPointHitObject.o \
Effect.o LinearMapPitchShifter.o MapPitchShifter.o \
IoEvent.o IoEventProcessor.o PanelEvent.o IoCommunicator.o \
InstrumentEvent.o InstrumentEventProcessor.o InstrumentController.o \
PlayfieldEvent.o PlayfieldEventProcessor.o PlayfieldController.o \
GameEvent.o StartGameEvent.o StopSystemEvent.o SystemEvent.o SystemEventHandler.o \
TimeEvent.o TimeEventProcessor.o TimeControllerController.o \
ResourceStoreWorkingSm.o SheetmusicConverter.o SheetmusicManager.o SheetmusicMetadata.o SheetmusicPostprocessor.o SheetmusicStore.o WorkingSheetmusic.o \
SimpleSmDecoder.o SmDecoder.o FileReader.o Pattern.o PatternGenerator.o \
SheetmusicSelectPanel.o VolumeController.o SoundSelectPanel.o \
\
Instrument.o HasPitch.o MeteoPiano.o Piano.o VirtualMeteoPiano.o CompositeMeteoPiano.o \
SimpleSoundBindingSet.o SoundBinding.o SoundBindingSet.o PianoInputManager.o \
\
FileSystem.o ProgramInitializer.o \
\
MeteoGameDesktop.o Program.o \
MeteoLightBoardV1.o bcm2835.o MeteoBitbangDisplayDevice.o MeteoSpidevDisplayDevice.o MeteoKeyboardDevice.o MeteoPanelDevice.o MeteoPanelBoardV1.o pi2c.o \
MeteoBluetoothDevice.o MeteoBluetoothPhoneV1.o MeteoPacketConverterV1.o sdp.o \
\
MeteorGame.o MeteorConfigManager.o MeteorInputManager.o MeteorPlayfield.o \
MeteorRuleset.o MeteorRulesetExecutor.o MeteorJudgement.o MeteorHitWindow.o MeteorReplayRecorder.o MeteorReplayFrame.o \
MeteorResult.o \
AutoPedalModifier.o MusicGameModifier.o HandModifier.o MeteorDifficultyModifier.o RepeatPracticeModifier.o FallSpeedModifier.o ClockRateModifier.o \
MeteorScoreProcessor.o \
SustainPedalLightRingOutputer.o SustainPedalLightRingPanelMessage.o \
MeteorEventProcessorMaster.o MeteorNoteControlPointHitObject.o MeteorInputKeyControlPointHitObject.o \
ExplodeEffect.o ExplodeEffectMapper.o FallEffect.o FallEffectMapper.o EruptEffect.o EruptEffectMapper.o GlowLineEffect.o GlowLineEffectMapper.o TargetLineEffect.o TargetLineEffectMapper.o \
ExplodeMapAlgorithm.o FallMapAlgorithm.o EruptMapAlgorithm.o GlowLineMapAlgorithm.o TargetLineMapAlgorithm.o \
SustainPedalIoEvent.o SustainPedalLightRing.o SustainPedalLightRingIoCommunicator.o \
PianoEvent.o PianoEventProcessor.o PianoController.o PianoSoundEvent.o PianoSoundEventProcessor.o VirtualPianoController.o \
OctaveShiftEvent.o OctaveShiftEventProcessor.o OctaveShifter.o \
RepeatPracticeEvent.o RepeatPracticeEventProcessor.o RepeatPracticeController.o \
MeteorSheetmusicConverter.o MeteorSheetmusicPostprocessor.o MeteorPatternGenerator.o \
MeteorTimeController.o 


#Program.o Game.o \
#FrameworkConfigManager.o \
#Map.o renderer.o \
#Player.o Playfield.o Session.o Ruleset.o RulesetInfo.o \
#Scheduler.o Event.o EventProcessorMaster.o GameEvent.o StartGameEvent.o ControlPoint.o NoteControlPoint.o Effect.o \
#SystemEvent.o StopSystemEvent.o SystemEventHandler.o \
#SheetmusicConverter.o SheetmusicManager.o SheetmusicMetadata.o SheetmusicPostprocessor.o WorkingSheetmusic.o \
#SmDecoder.o SimpleSmDecoder.o FileReader.o Pattern.o PatternGenerator.o \
#WS2812v10Renderer.o dma.o pwm.o ws2811.o mailbox.o pcm.o rpihw.o \
#MeteorGame.o MeteorConfigManager.o MeteorPlayfield.o MeteorRuleset.o MeteorRulesetExecutor.o \
#ExplodeEffect.o ExplodeEffectMapper.o FallEffect.o FallEffectMapper.o GlowLineEffect.o GlowLineEffectMapper.o TargetLineEffect.o TargetLineEffectMapper.o \
#ExplodeMapAlgorithm.o FallMapAlgorithm.o GlowLineMapAlgorithm.o TargetLineMapAlgorithm.o \
#MeteorSheetmusicConverter.o MeteorPatternGenerator.o \
#FileSystem.o MtoObject.o ProgramInitializer.o \
#Cachable.o ChildAddable.o HasParent.o Loadable.o LoadStateHandler.o \
#Updater.o Updatable.o



all:$(TARGET)

$(TARGET): $(OBJS) 
	$(CC) $(OBJS) -o $@ -pthread -lstdc++fs -lbass -lbass_fx -lbluetooth
	
.c.o:
	$(CC) $(INCLUDE) $(CFLAGS) -c -o $@ $< 	
	
.cpp.o:
	$(CC) $(INCLUDE) $(CFLAGS) -c -o $@ $< 

clean:
	rm -f *.o $(TARGET)